### ISSUE TITLE
Missing  tools/test_net.py

### ISSUE THREAD

**Issue by frinklai** [ivalab/grasp_multiObject_multiGrasp#14]
Dear Fu,
I forked this project and tried to train by the [steps](https://github.com/ivalab/grasp_multiObject_multiGrasp#train) that shown in readme.md.
But, there is an error when I execute  
`./experiments/scripts/train_faster_rcnn.sh 0 graspRGB res50`

I found the reason is there is no `test_net.py `in ` ./tools`
Can you please show  `test_net.py ` for us ?
Thank you very much for your help.
Best Regard

**Comment by fujenchu** [comment]
Hi frinklai,

My apology for late reply. 
In our implementation I didn't use 'test_net.py' mainly because we use different (Jaccard) metric instead of conventional object detection metric (for detail please refer to our [article](https://arxiv.org/abs/1802.00520)). For evaluation, please use our evaluation code in the repo. 

Please let me know if you have any further question.
Best,
Fu-Jen
