### ISSUE TITLE
physical grasp

### ISSUE THREAD

**Issue by HanwenCao** [ivalab/grasp_multiObject_multiGrasp#20]
The 5-dimensional grasp rectangle is defined in a 2D space. Then I was wondering how could the end-effector know the 'z' value of a grasp in physical grasp experiments. I am very new to grasp planning. Thank you so much!

**Comment by pv33** [comment]
Since there is a depth image, the 3D location can be recovered.  Usually we assume that the robot arm will be reaching down from above (moving downwards along z-axis). That means the orientation of the hand is pointing straight down so that only yaw matters (not pitch, not roll or equivalently no rotation about x-axis nor y-axis, only z-axis).  Under these assumptions, the 2D grasp rectangle specifies all missing information when post-processed using the depth image.

There should be code in a repository somewhere (maybe in the ivaROS organization on GitHub.com) that will take DeepGrasp outputs and convert them into motion plans to execute for grasping. I can't say 100%.  It should be this [repository](https://github.com/ivaROS/ros_deep_grasp).

**Comment by HanwenCao** [comment]
Thank you Professor. You comment helps me a lot. The link is also helpful. (What a coincidence! Can't believe you are replying. I am Hanwen :) ) I am going to close the issue since the problem is perfectly solved. Thank you!
